### ISSUE TITLE
Self closing tag is replaced with string '[removed]'

### ISSUE THREAD

**Issue by alexandre-roitman** [leizongmin/js-xss#105]
When calling XSS on a self closing tag (ex: meta tag)

var result = xss('<meta content="my page" />', {
            stripIgnoreTagBody: true
});

result will be '[removed]'

Can this issue be handled?

**Comment by alexandre-roitman** [comment]
@leizongmin can you assist?

**Comment by leizongmin** [comment]
You can specify a custom `onIgnoreTag` method to do such things. 
Refer to  https://github.com/leizongmin/js-xss/blob/master/lib/default.js#L315 and https://github.com/leizongmin/js-xss/blob/master/lib/xss.js#L136
