### ISSUE TITLE
请教大牛，这个问题怎么去解决？

### ISSUE THREAD

**Issue by tuhuason** [leizongmin/js-xss#107]
` <a href="http://jsxss.com/%3Cscript%3Ealert(document.cookie)%3C/script%3E">http</a>`
怎么去过滤呢？

**Comment by leizongmin** [comment]
这个你只能自定义过滤URL的规则。`xss`模块默认过滤的是对当前 HTML 页面有危害的攻击，`http://jsxss.com/%3Cscript%3Ealert(document.cookie)%3C/script%3E` 这个 URL 能不能被利用是要看新目标页面有没有做处理，当时当前页面是管不到的。
