### ISSUE TITLE
Refused to execute scrip

### ISSUE THREAD

**Issue by GZWZC** [leizongmin/js-xss#110]
i import xss.js in my html,
```
<script  src="https://raw.github.com/leizongmin/js-xss/master/dist/xss.js"></script>
<script>
// 使用函数名 filterXSS，用法一样
console.log(filterXSS('<a href="#" onclick="alert(/xss/)">click me</a>'));
</script>
```

chrome console
`Refused to execute script from 'https://raw.github.com/leizongmin/js-xss/master/dist/xss.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

how sholud i do?

**Comment by leizongmin** [comment]
Please download the `https://raw.github.com/leizongmin/js-xss/master/dist/xss.js` on your local, and use `<script  src="xss.js"></script>` to load the `xss.js` file.
