### ISSUE TITLE
xss把我图片的src属性过滤掉了。。

### ISSUE THREAD

**Issue by zhubenjie** [leizongmin/js-xss#116]
![11](https://user-images.githubusercontent.com/21832438/31597422-d20ea004-b27a-11e7-9e30-1d0be4bb315c.jpg)
![22](https://user-images.githubusercontent.com/21832438/31597425-d6e205ee-b27a-11e7-8833-d0421b0e22a0.jpg)

**Comment by leafiy** [comment]
我还想过滤src呢，你怎么配置的
