### ISSUE TITLE
vue 中使用时设置关闭css，仍然不行

### ISSUE THREAD

**Issue by cmideal** [leizongmin/js-xss#117]
vue中调用后加入关闭删选的css，仍然会去掉style

**Comment by leizongmin** [comment]
默认的白名单是禁止`style`属性的，你需要传入一个自定义的`whitelist`来允许相应标签的`style`。此时针对`style`样式条目的过滤器才会生效，如果关闭了`css`，则不会对`style`的值做任何过滤。
