### ISSUE TITLE
This module does not work in a Web Worker

### ISSUE THREAD

**Issue by GenaBitu** [leizongmin/js-xss#124]
What I expected to be able to use in a **Web worker**:

```js
onmessage = process;
importScripts('/node_modules/xss/dist/xss.min.js');

function process(message)
{
	var html = xss.filterXSS(message.data);
	postMessage(html);
}
```

What happened: `xss` is undefined. I also tried using just `filterXSS`, but that fails too.

**Comment by leizongmin** [comment]
Hi, the newest version `xss@1.0.1` can work on web worker environment.

```
// just use filterXSS
var html = filterXSS(message.data);
```

**Comment by GenaBitu** [comment]
Just tried it, works like a charm, thank you very much!
