### ISSUE TITLE
Whitelist needs to be exported to browsers

### ISSUE THREAD

**Issue by bnovc** [leizongmin/js-xss#125]
Currently you can't access it, so you can only overwrite options and not extend them.

e.g.

 446 // using `xss` on the browser, output `filterXSS` to the globals
 447 if (typeof window !== "undefined") {
 448   window.filterXSS = module.exports;
 449   window.getDefaultWhiteList = exports.getDefaultWhiteList;
 450 }

**Comment by bnovc** [comment]
I also had to edit your protocol whitelist to make this work for me, since I wanted links to a custom protocol. There was no option for this.

Seems okay now. Thanks for the module.

**Comment by leizongmin** [comment]
you are welcome.
