### ISSUE TITLE
Can I ignore style tag

### ISSUE THREAD

**Issue by Sophia-nguyen** [leizongmin/js-xss#128]
Hi,

How can I ignore style tag when use filterXSS().

code: 
    `<script>alert("test")</script><style>h1{color: red}</style><div>test</div>`
result: 
    `"&lt;script&gt;alert("test")&lt;/script&gt;&lt;style&gt;h1{color: red}&lt;/style&gt;<div>test</div>"`
**expected**: 
    `"&lt;script&gt;alert("test")&lt;/script&gt;  <style>h1{color: red}</style> <div>test</div>"`

Any option for  this case?
Thanks,

**Comment by leizongmin** [comment]
use the `stripIgnoreTagBody` option, see https://github.com/leizongmin/js-xss#filter-out-tags-and-tag-bodies-not-in-the-whitelist
