### ISSUE TITLE
 Upgraded xss to 1.00, got error: pontentially sensitive files: .unpack.js.swp lint-snap-v2_iffy_files snapcraft

### ISSUE THREAD

**Issue by xet7** [leizongmin/js-xss#139]
https://forum.snapcraft.io/t/upgraded-xss-to-1-00-got-error-pontentially-sensitive-files-unpack-js-swp-lint-snap-v2-iffy-files/5584

> ogra: looks like someone had unpack.js open in vim when creating the xss package and the snap check tools consider the swap file as potentially dubious … if you are sure the file doesnt come from an editing session you had yourself, i’d contact the xss packager to fix it.

> xet7: I have not edited unpack.js ever. I’ll contact packager.

**Comment by leizongmin** [comment]
It seems the `xss` package does not include this file.

I try `npm i xss` command to install this package, and this is the installed files under the `node_modules` directory below:

```text
.
├── commander
│   ├── CHANGELOG.md
│   ├── LICENSE
│   ├── Readme.md
│   ├── index.js
│   ├── package.json
│   └── typings
│       └── index.d.ts
├── cssfilter
│   ├── LICENSE
│   ├── README.md
│   ├── lib
│   │   ├── css.js
│   │   ├── default.js
│   │   ├── index.js
│   │   ├── parser.js
│   │   └── util.js
│   └── package.json
└── xss
    ├── LICENSE
    ├── README.md
    ├── README.zh.md
    ├── bin
    │   └── xss
    ├── dist
    │   ├── test.html
    │   ├── xss.js
    │   └── xss.min.js
    ├── lib
    │   ├── cli.js
    │   ├── default.js
    │   ├── index.js
    │   ├── parser.js
    │   ├── util.js
    │   └── xss.js
    ├── package.json
    └── typings
        └── xss.d.ts

9 directories, 29 files
```

**Comment by xet7** [comment]
Ok, seems to be that some other dependency has this file.
