### ISSUE TITLE
DedicatedWorkerGlobalScope is not defined

### ISSUE THREAD

**Issue by bigStuart** [leizongmin/js-xss#140]
![image](https://user-images.githubusercontent.com/14803721/40490436-16702990-5f9e-11e8-805f-e96e9be64f5c.png)

**Comment by Asvarox** [comment]
Yes, this was introduced with #124, specifically the `isWorkerEnv` function introduced https://github.com/leizongmin/js-xss/commit/723b307a32541044e4f4dcbb260c34b3168e87f2 commit. I'm preparing a PR with the fix

**Comment by leizongmin** [comment]
Please try the new version `xss@1.0.3`

**Comment by bigStuart** [comment]
ok, thank you! @Asvarox @leizongmin
