### ISSUE TITLE
怎么防御这种case

### ISSUE THREAD

**Issue by ZH3FENG** [leizongmin/js-xss#160]
URL：http://example.com/user/info?'-alert(99)-'

Node页面：
<script>
           xxx.function({
                currentURL: '${url}'
            })
</script>

渲染后HTML页面：
<script>
           xxx.function({
                currentURL: 'http://example.com/user/info?'-alert(99)-''
            })
</script>
alert(99)执行。

**Comment by leizongmin** [comment]
这个模块主要是针对HTML代码过滤一般的XSS漏洞，像你这个例子可能并不适用。建议自己针对性地写一些代码来过滤
