### ISSUE TITLE
src 引入时，报undefined

### ISSUE THREAD

**Issue by sunfutao** [leizongmin/js-xss#166]
<script src="https://raw.github.com/leizongmin/js-xss/master/dist/xss.js"></script>
这种方式引入时，浏览器警告CORB，MIME type 为 text/plain，无法引入
![image](https://user-images.githubusercontent.com/35865208/56479137-21924300-64e6-11e9-88f4-c1f52437dbfa.png)

**Comment by leizongmin** [comment]
建议通过 `https://unpkg.com/xss@1.0.6/dist/xss.min.js` 来引入
