### ISSUE TITLE
Labels on Github do not correspond to releases on ntpm

### ISSUE THREAD

**Issue by Kjir** [leizongmin/js-xss#168]
The latest tag on Github is `v1.0.3`, whereas on NPM the latest version is [`1.0.6`](https://www.npmjs.com/package/xss).

Is it a legitimate release? If it is, could you please add the correct tags on Github as well so that we may easily inspect the code at that point?

**Comment by leizongmin** [comment]
I am very sorry. Now I have add the missing tag `v1.0.6`.
