### ISSUE TITLE
jsxss.com is not working because of lang forward rules

### ISSUE THREAD

**Issue by sijanec** [leizongmin/js-xss#182]
off-topic, but still related:

script in index HTML file on jsxss.com page will redirect a client to an unexistent folder based on their client's (browser's) language code.

for example if my language is `sl`, I would be redirected to /sl/index.html, which will result in a 404. very annoying.

```
  | <script>
-- | --
  | var lang = 'en';
  | try {
  | lang = navigator.language.split('-')[0];
  | } catch (err) {
  | alert(err);
  | }
  | location.replace('/' + lang + '/index.html');
  | </script>
  |  
```

**Comment by leizongmin** [comment]
Thank you for your report. Just fixed this problem.
