### ISSUE TITLE
image src = base64 miss

### ISSUE THREAD

**Issue by Leonard-Li777** [leizongmin/js-xss#184]
as title

**Comment by sijanec** [comment]
It looks like the poster of this issue doesn't care about it being fixed, as seen from his behaviour, not showing any interest at all.

I understood his question and have the same problem. Image tags get base64 encoded data stripped out. Why would base64 encoded image be an issue? If not, please allow it.

Thanks in advance"!

**Comment by leizongmin** [comment]
Sorry, so late to deal with this problem. I have released a new version `v1.0.7` and added image data-url to the default configuration.
