### ISSUE TITLE
白名单设置了允许标签内的style，正常显示style的内容，但是把style里的line-height过滤掉了

### ISSUE THREAD

**Issue by qqq5833547** [leizongmin/js-xss#192]
你好，白名单设置了允许标签内的style，正常显示style的内容，但是把style里的line-height过滤掉了

**Comment by zhixinpeng** [comment]
![image](https://user-images.githubusercontent.com/24643457/81905781-cd2d9a00-95f7-11ea-8126-9b44f09c9369.png)
需要把css设置为 false

**Comment by qqq5833547** [comment]
> ![图片](https://user-images.githubusercontent.com/24643457/81905781-cd2d9a00-95f7-11ea-8126-9b44f09c9369.png)
> 需要把css设置为false
已经解决，忘记关issues了，谢谢
