### ISSUE TITLE
Namespaced tags are escaped

### ISSUE THREAD

**Issue by arildm** [leizongmin/js-xss#199]
Tags like `<o:p></o:p>` get escaped. They should perhaps be filtered away instead?

This particular example comes from copying MS Word-generated HTML. Related: #196

**Comment by leizongmin** [comment]
This is because tag `o:p` does not in the default `whiteList`. 
If you want to allow this tag, change the `whiteList` options.
Ref: https://github.com/leizongmin/js-xss#whitelist

**Comment by levyleo** [comment]
@leizongmin  `whiteList` not work for `<!--<![endif]-->`, because this code will parse as tag `![endif]--` when `parser.parseTag`

**Comment by arildm** [comment]
My problem was that the tag was escaped instead of removed. Problem solved by adding [`onIgnoreTag: () => ""`](https://github.com/leizongmin/js-xss#customize-the-handler-function-for-tags-not-in-the-whitelist) to the config. I should have RTFM :)
