### ISSUE TITLE
Whitelist a tag with any attribute

### ISSUE THREAD

**Issue by AdrianNeatu** [leizongmin/js-xss#214]
Is there a way to whitelist a tag with any attribute? From what I see, now, I have to specify all attributes I want for a tag in whitelist.

**Comment by gaoyaoman** [comment]
Convenience must sacrifice safety.

**Comment by gaoyaoman** [comment]
> Is there a way to whitelist a tag with any attribute? From what I see, now, I have to specify all attributes I want for a tag in whitelist.

Convenience must sacrifice safety.

**Comment by AdrianNeatu** [comment]
@gaoyaoman but does it? :) you speak like someone who didn't have to whitelist SVG embeding ....
I would've hope for something like
`whitelist : { svg: '*'}` (for all svg inner tags of course)
Or something like that.

**Comment by leizongmin** [comment]
You can try to setup a custom `onIgnoreTagAttr` function to allow any attributes, ref:  https://github.com/leizongmin/js-xss/#customize-the-handler-function-for-attributes-not-in-the-whitelist

Here is an example: https://github.com/leizongmin/js-xss/issues/118#issuecomment-352865144
