### ISSUE TITLE
[Question] Why the `muted` attribute of the `video` tag not in the default whitelist?

### ISSUE THREAD

**Issue by maltoze** [leizongmin/js-xss#227]
Is there a security risk with the `muted`?

Thanks.

**Comment by leizongmin** [comment]
I have published a new version `xss@1.0.9` including the following changes:

- [Fix whitespace bypass #218](https://github.com/leizongmin/js-xss/pull/218/files) by @TomAnthony
- [Add `<summary>` to default whitelist #216](https://github.com/leizongmin/js-xss/pull/216) by @spacegaier
- [Add `<figure>` and `<figcaption>` to default whitelist](https://github.com/leizongmin/js-xss/pull/220) by @daraz999
- Add `<audio crossorigin muted>`, `<video crossorigin muted playsinline poster>` to default whitelist
- Add `<strike>` to default whitelist
- Fix: typings IWhiteList allow any tag name
- Fix: typings `onTag` options
