### ISSUE TITLE
[Question] How to use typings in browser-targeting code?

### ISSUE THREAD

**Issue by marekdedic** [leizongmin/js-xss#229]
Hi, I am using `xss` in code intended to run in the browser (so no `import` or `require`...). I'm trying to get the following to work:

```ts
/// <reference types="xss" />
declare function xssOptions(): xss.IFilterXSSOptions;
```

However, I'm getting `error TS2503: Cannot find namespace 'xss'.` Is this an issue with the typings? Or am I using it wrong?

Thanks!

**Comment by leizongmin** [comment]
try use upper case `XSS`:

```
declare function xssOptions(): XSS.IFilterXSSOptions;
```
