### ISSUE TITLE
HTML comment tags are encoded

### ISSUE THREAD

**Issue by andrey-skl** [leizongmin/js-xss#230]
1. Run XSS via the following params: `filterXSS('<!-- foo -->', {allowCommentTag: true})`

Expected output: `<!-- foo -->`
Actual output: `&lt;!-- foo --&gt;`

Version: `xss@1.0.8`

**Comment by ittybittykitty** [comment]
I have this issue too.

expected output: `<!--[some comment]-->`
Actual output:  `&lt;!--[some comment]--&gt;`

**Comment by andrey-skl** [comment]
@leizongmin Hello!

I can see that the fix is actually reverted here https://github.com/leizongmin/js-xss/commit/352ae5331f2057a8e7dd198be703b3375ec98206

Can you please let us know why it is not possible to fix?

Thanks!

**Comment by leizongmin** [comment]
Hi @andrey-skl 
This is because the RegExp `/(?<!--)>/g` will caused `SyntaxError: Invalid regular expression: invalid group specifier name` on Safari.
Here is the related issue: https://github.com/leizongmin/js-xss/issues/259
