### ISSUE TITLE
请问是否不能保留CSS样式？如果富文本编辑的内容有行内样式的话

### ISSUE THREAD

**Issue by femaimi9527** [leizongmin/js-xss#232]
感谢xss团队/作者的贡献，
在使用中遇到几个问题：
1、请问是否不能保留CSS样式？如果富文本编辑的内容有行内样式的话，目前我的使用经历是提交富文本编辑的内容中，html标签是带有行内样式的，然后发现通过xss处理后，行内样式不见了；
2、请问xss.whitelist 通过哪个路径能找到？
谢谢！

**Comment by leizongmin** [comment]
默认的白名单里面，每个标签都不允许 `style` 属性的，所以行内样式会被过滤掉。你可以定制自己的白名单，给这些标签都加上 `style` 属性。另外，对于行内的样式（`style` 属性）还会自动启用一个 CSS 过滤白名单。具体可阅读以下资料：

- [自定义白名单参考文档](https://github.com/leizongmin/js-xss/blob/master/README.zh.md#%E7%99%BD%E5%90%8D%E5%8D%95)
- [自定义 CSS 过滤器](https://github.com/leizongmin/js-xss/blob/master/README.zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89-css-%E8%BF%87%E6%BB%A4%E5%99%A8)
- [默认的白名单参考](https://github.com/leizongmin/js-xss/blob/master/lib/default.js#L11)

**Comment by femaimi9527** [comment]
好的，非常感谢您的悉心解答！祝项目越发valuable && unreplacable ！
