### ISSUE TITLE
Commander version doesn't exist

### ISSUE THREAD

**Issue by MMMikeM** [leizongmin/js-xss#235]
Hi there

I see that commander@^2.20.3  is referenced, but this version appears to have been unpublished

https://www.npmjs.com/package/commander?activeTab=versions

Can this be rectified by changing it to an earlier version, such as 2.20.0?

Thanks

**Comment by leizongmin** [comment]
Hi @MMMikeM , I see that the latest version of 2.x is 2.20.3
![image](https://user-images.githubusercontent.com/841625/130559126-7b8f0d19-da35-44c0-af28-9e334901868e.png)

**Comment by MMMikeM** [comment]
I probably should have noticed that. I was looking at this, in the version history

![image](https://user-images.githubusercontent.com/50731334/130565698-471db5b6-f2ea-41d2-89b6-9e7a685fb425.png)


This stems from my team getting this error - there must be something underlying 😊

![image](https://user-images.githubusercontent.com/50731334/130565600-5b989650-7ef7-4b5e-bf21-2bf3c4538d42.png)
