### ISSUE TITLE
无法过滤 0 宽控制符

### ISSUE THREAD

**Issue by huanglong** [leizongmin/js-xss#27]
如下：

```
'Cats & Dogs '.replace(/[\u0000-\u001F]|\u007F/g, '')
```

把这句贴到 chrome console 里会出现以下报错：

![image](https://cloud.githubusercontent.com/assets/670360/5795818/ccc73ad6-9f4d-11e4-9648-f3ece049d231.png)

原因是在 Dogs 后面，可以用鼠标移动看看，有一个宽度为 0 的不可见字符，用户拷贝了带这样字符的文本，通过表单提交到你的后台，通过 xss() 后没过滤掉，再存到到数据库，最后以 json 变量的形式输出到 html 中，就会因为解析出错而破坏整个 json 结构，从而造成 bug。

这种字符通过 xss 能过滤掉么？

**Comment by leizongmin** [comment]
已增加自动清除不可见字符：https://github.com/leizongmin/js-xss/commit/97d0bdf5160611b79e24c6a0894ef4a28b80db80

使用最新版本 `xss@0.1.18` 即可。

**Comment by leizongmin** [comment]
目前已改为过滤时设置stripBlankChar=true来过滤不可见字符，默认不过滤。
过滤不可见字符的规则为 ASCII码<32 || ASCII码=127 且非回车或换行符。
版本 `xss@0.1.20`

```javascript
xss('a\u0000\u0001\u0002\u0003\r\n b', {stripBlankChar: true})
// 结果为 "a\r\n b"
```

详见 https://github.com/leizongmin/js-xss/commit/6249d4cf2a70c938fe3d8d12d0e7b9e43c0eba81
