### ISSUE TITLE
CSS白名单过滤

### ISSUE THREAD

**Issue by leizongmin** [leizongmin/js-xss#29]
针对标签style属性过滤，可配置允许某些CSS样式

**Comment by chenqing** [comment]
遇到同样得问题，div里面的style给去掉了，纠结，期待可以解决

**Comment by leizongmin** [comment]
`xss@0.2.0`使用[cssfilter模块](https://github.com/leizongmin/js-css-filter)来过滤`style`属性，允许部分CSS代码（通过白名单来配置），你可以安装这个新版本试试。

+ `cssfilter`模块项目地址：https://github.com/leizongmin/js-css-filter
  + 默认的CSS白名单：https://github.com/leizongmin/js-css-filter/blob/master/lib/default.js

+ 如果要在`xss`模块中自定义CSS白名单，在过滤时传入`options.css`参数即可（`options.css`相当于`css`模块的`options`）

+ __由于还不确定现有的默认CSS白名单是否足够安全，所以`xss`模块默认的白名单里并没有允许`style`属性，如果要测试得先在白名单中允许`style`属性之后，才会启用新的程序来过了`style`属性的值__

------

说明：比如CSS中的`position`被认为是不安全的，因为`display:block; position:fixed; top:0; left:0; width:100%; height:100%; background:#000;`这样的一段CSS代码就会把当前的网页变成一个全黑的页面，所以`position`应该被过滤掉。

**Comment by masquevil** [comment]
可以在默认的白名单下，额外允许某些标签和熟悉么？
比如对我来说不用过滤 input 和所有的 style

**Comment by leizongmin** [comment]
+ 可以修改白名单，增加`input`标签
+ 或者通过自定义`onTagAttr`等一系列函数允许某些特例，详看文档：https://github.com/leizongmin/js-xss/blob/master/README.zh.md
