### ISSUE TITLE
Is xss(content) safe to be used in attributes?

### ISSUE THREAD

**Issue by bitinn** [leizongmin/js-xss#33]
It appears this module targets HTML input/output, I should always do

`xss('<a href="' + url +'">')`

instead of

`<a href="xss(url)">link<a/>`

right?

This also means I should always do `json data -> template render -> xss filter -> append`, instead of `json data -> xss filter -> template render -> append` right?

**Comment by leizongmin** [comment]
__NO.__
`xss` is use to filter HTML, for example, the folllowing HTML is safe:

```html
javascript:alert(/xss/);
```

because it just a text, not JavaScript code, so `xss()` will returns the original HTML. But if you use in attributes, for example:

```html
<a href="xss(url)">link<a/>
```

the output will be:

```html
<a href="javascript:alert(/xss/);">link<a/>
```

__it is not the right way.__

**Comment by bitinn** [comment]
Thx, that'a all I needed to know.

**Comment by leizongmin** [comment]
if you want to filter the attributes value, you can use the  function `xss.safeAttrValue()` ([see the code](https://github.com/leizongmin/js-xss/blob/master/lib/default.js#L141))

for example: 

```javascipt
xss.safeAttrValue('a', 'href', 'javascript:alert(/xss/);');
```
