### ISSUE TITLE
能添加黑名单吗？

### ISSUE THREAD

**Issue by saymy** [leizongmin/js-xss#34]
如题。

**Comment by leizongmin** [comment]
`xss` 模块设计的初衷是根据白名单来过滤，但还是允许通过一些自定义的函数来『曲线』完成『黑名单』过滤，大概原理如下：

当标签不在白名单时，`xss`模块会尝试调用`onIgnoreTag`来处理，此时有机会自主选择是将此段HTML过滤掉还是返回一段新的HTML。

详看文档：

+ [允许标签以data-开头的属性 示例](https://github.com/leizongmin/js-xss/blob/master/README.zh.md#允许标签以data-开头的属性)
+ [允许名称以x-开头的标签 示例](https://github.com/leizongmin/js-xss/blob/master/README.zh.md#允许名称以x-开头的标签)
+ [`onIgnoreTag`参数说明](https://github.com/leizongmin/js-xss/blob/master/README.zh.md#自定义匹配到不在白名单上的标签时的处理方法)
+ [`onIgnoreTagAttr`参数说明](https://github.com/leizongmin/js-xss/blob/master/README.zh.md#自定义匹配到不在白名单上的属性时的处理方法)
