### ISSUE TITLE
似乎并没有识别未闭合标签的功能

### ISSUE THREAD

**Issue by nanwangjkl** [leizongmin/js-xss#38]
![aaa](https://cloud.githubusercontent.com/assets/4200349/8985058/effc6fd8-3707-11e5-91d6-1ee427b70d3c.png)
我这里有些文本含有未闭合的a标签，导致其他的html内容都不能正确显示了……
试了试XSS，好像也不能识别出来。。。

**Comment by leizongmin** [comment]
`xss`的主要功能是过滤XSS代码，并不考虑各种畸形HTML的情况
