### ISSUE TITLE
Not work with RequireJS

### ISSUE THREAD

**Issue by martin-liu** [leizongmin/js-xss#42]
The xss.js and xss.min.js file in dist folder actually returns FilterCSS. 
Because there's two define in 
https://github.com/leizongmin/js-xss/blob/master/dist%2Fxss.js#L447
and https://github.com/leizongmin/js-xss/blob/master/dist%2Fxss.js#L1432

I think it's better to split it to two files to make sure AMD works fine.

**Comment by leizongmin** [comment]
Can you help me to fix this problem? Send me a pull request would be better

**Comment by leizongmin** [comment]
The related project `css-filter`: https://github.com/leizongmin/js-css-filter

**Comment by dimarwix** [comment]
Hey @leizongmin , please see PR https://github.com/leizongmin/js-css-filter/pull/3

**Comment by leizongmin** [comment]
@martin-liu  Has merged the pull request and published a new version, please try the newest version `xss@0.2.11`, if any question please let me know.
@dimarwix Thanks very much 👍

**Comment by dimarwix** [comment]
@leizongmin works like a charm! Thanks!
