### ISSUE TITLE
文档缺少 CSS 配置的说明 

### ISSUE THREAD

**Issue by zhangbobell** [leizongmin/js-xss#46]
非常感谢能提供如此方便的工具，不过在使用的过程中遇到了一个问题：
我写了允许 `<p>` 标签上有 `style` 属性，但是结果是 `style` 属性里的 `line-height` 属性被过滤掉了。

看了下代码，我看到里面 css 的 xss 过滤用的是另外一个库叫 `cssfilter`，里面提供了配置 css 属性白名单的功能，但是在说明文档里面没有提到。

为了以后的人能少踩一个坑，建议能加上一点关于 css 的 xss 配置说明。

**Comment by leizongmin** [comment]
已处理。https://github.com/leizongmin/js-xss/commit/afe364cc3d0a4b89061ab5d29679f0f1d058ab91
