### ISSUE TITLE
XSS whiteList issue.

### ISSUE THREAD

**Issue by gauravnayak210** [leizongmin/js-xss#52]
Whenever I use `whiteList` option all html content is converted into encoded string instead of sample html.

I have used below string:

`var source = '<p>Hotel Kadi Palace is located in the <strong>heart </strong>of the <strong>historic center of Florence </strong>';
var html = xss(source, {
  whiteList:          ['href','target']
});
console.log(html);`

So I just want to know whether it is functionality or minor bug, and what should I do to get plain html here.

**Comment by leizongmin** [comment]
When input below HTML:

```html
<p>Hotel Kadi Palace is located in the <strong>heart </strong>of the <strong>historic center of Florence </strong>
```

What's your expected result? Please write the expected HTML here to help me understanding what you mean.

**Comment by gauravnayak210** [comment]
Hi,
My expected result is the same as you sent:
<p>Hotel Kadi Palace is located in the <strong>heart </strong>of the
<strong>historic center of Florence </strong>

But I found it encoded like :  &lt;p&gt; Hotel Kadi...

Regards,
Gaurav Nayak.

**Comment by leizongmin** [comment]
Normally, you don't need to specify the `whiteList` option. For example:

```javascript
var source = '<p>Hotel Kadi Palace is located in the <strong>heart </strong>of the <strong>historic center of Florence </strong>'; 
var html = xss(source);
console.log(html);
```

It will use the default configurations to filter the HTML. The `whiteList` option allows you to define your custom whiteList. You can use `xss.getDefaultWhiteList()` to get a default whiteList, and modify it. For example:

```javascript
// get default whiteList
var whiteList = xss.getDefaultWhiteList();
// modify it
whiteList.tag = ['attribute1', 'attribute2'];
// xss()
var source = '<p>Hotel Kadi Palace is located in the <strong>heart </strong>of the <strong>historic center of Florence </strong>'; 
var html = xss(source, {whiteList: whiteList});
console.log(html);
```

**Comment by gauravnayak210** [comment]
Hi,

Let me tell you my actual problem, I want to display link in my html  with
its value.(for example <a href="xyz.jpg" >).

For that I add *href* tag in whitelist.

I also tried what you sent yesterday, I added href tag in `getDefaultWhiteList`
but did not get href value.

My html is:

'<p>Hotel Kadi Palace is located in the <a href="xyz.jpg" >click here</a>
<strong>heart </strong>of the <strong>historic center of Florence
</strong><script> alert("xss")</script>'

Expected OP:
'<p>Hotel Kadi Palace is located in the <a href="xyz.jpg" >click here</a>
<strong>heart </strong>of the <strong>historic center of Florence
</strong>&lt;script&gt; alert("xss")&lt;/script&gt;'


Regards,
Gaurav Nayak.

**Comment by leizongmin** [comment]
The `href` attribute of tag `<a>`  is allow by default. For example:

```javascript
xss('<a href="/xyz.jpg" >')
// will results '<a href="xyz.jpg">'
```

But, if the value of `href` attribute is not start with `http://`, `https://`, `mailto:`, `/` or `#` than it will removed. In your example codes:

```javascript
xss('<a href="xyz.jpg" >');
// will results '<a href>'
```

**Comment by leizongmin** [comment]
There is a way to let you change the default `href` attribute filter:

```javascript
// custom  safeAttrValue function
function safeAttrValue(tag, name, value, cssFilter) {
  // only when the tag is 'a' and attribute is 'href'
  // then use your custom function
  if (tag === 'a' && name === 'href') {
    // only filter the value that start with 'javascript:'
    if (/^javascript:/ig.test(value)) {
      return '';
    }
    return value;
  } else {
    // use the default safeAttrValue function to process it
    return xss.safeAttrValue(tag, name, value, cssFilter);
  }
}

// specify the safeAttrValue option
xss('<a href="xyz.jpg" > ', { safeAttrValue: safeAttrValue });
// will results '<a href="xyz.jpg">'

xss('<a href=" Javascript:alert(/xss/)" > ', { safeAttrValue: safeAttrValue });
// will results '<a href>'
```

**Comment by gauravnayak210** [comment]
This really make sense.

Thank you very much.
