### ISSUE TITLE
Is js-xss production ready?

### ISSUE THREAD

**Issue by petermikitsh** [leizongmin/js-xss#53]
Has this package been reviewed by any security firm(s)? I looked through the README but couldn't find any information on the topic. I'm kind of surprised, given that this package has over 1,000 stars, it seems like it is widely used.

I've come across various NPM packages that escape strings, but I'm not sure which is the best to go with. Obviously there is no 100% guarantees in security, but this package seems promising for my use case.

I'd appreciate input from the maintainers or from other package users who are concerned with XSS.

**Comment by leizongmin** [comment]
As far as I know, many Chinese company are using this package in their products. And there is also some open source project:

+**nodeclub** - A Node.js bbs using MongoDB - https://github.com/cnodejs/nodeclub
+ **cnpmjs.org** - Private npm registry and web for Enterprise - https://github.com/cnpm/cnpmjs.org

But this package has never been reviewed by any security firm yet. ( maybe someone reviewed it, but nobody tell me that. )

**Comment by petermikitsh** [comment]
@leizongmin Thanks for the info! It might be cool to mention some of the larger / well-known users of this project in the `README`, but I'll leave that you.

**Comment by leizongmin** [comment]
Thanks for your advice!
