### ISSUE TITLE
img src onerror xss 问题

### ISSUE THREAD

**Issue by bammoo** [leizongmin/js-xss#56]
你的这个 repo `xss(imgSrc)` 时，imgSrc 里面的这种代码`https://a"onerror=alert('hello')>` 要怎么过滤啊？

**Comment by leizongmin** [comment]
**`xss(html)`只过滤HTML代码**

比如参数`html`的值为`<img src="https://a"onerror=alert('hello')>`会被过滤成`<img src="https://a">`（因为在`img`标签内，`onerror`属性值是不在默认白名单中的，所以`onerror`属性部分被删除了）

但如果其值为`https://a"onerror=alert('hello')>`则结果是`https://a"onerror=alert('hello')&gt;`（只是将里面的`>`转移成了`&gt;`）

**Comment by bammoo** [comment]
明白了，谢谢

**Comment by rysinal** [comment]
为什么相对路径的a标签 href='./**.html'  和 img src='./xxx.jpg'    @属性值都被置空了呢？@leizongmin
