### ISSUE TITLE
文件中加入命令行使用時的 config.js 設定擋範例

### ISSUE THREAD

**Issue by irvin** [leizongmin/js-xss#57]
測試了幾次，才找出 config.js 的格式，建議加上一個範例檔案

> var options = {
>   whiteList:          [],        // empty, means filter out all tags
>   stripIgnoreTag:     true      // filter out all HTML not in the whilelist
> };

**Comment by leizongmin** [comment]
不太清楚你想要在哪里加上范例，你可以帮忙修改一下文档，然后提交一个 Pull Request 么？

**Comment by irvin** [comment]
主要是命令行的說明文件，在 xss -h 時，example 有包含 `$ xss -i origin.html -c config.js`，但是整個網站的文檔（中英文）中都找不到 config.js 的格式。

不知道以下文檔放在 github 的哪邊可改？
http://jsxss.com/zh/starter/cli.html

**Comment by leizongmin** [comment]
jsxss.com 网站的文件是在此项目的`gh-pages`分支上，你需要先`git checkout origin/gh-pages`分支，然后更改`zh/starter/cli.html`文件，相应地也要更改英文版的文件`en/starter/cli.html`

**Comment by leizongmin** [comment]
已添加 config.json 格式描述
