### ISSUE TITLE
td style vertical-align property gets removed

### ISSUE THREAD

**Issue by ankero** [leizongmin/js-xss#62]
I'm using the filter through js and just found an interesting error. It seems that the filter removes vertical-align property from td styles. Is there a reason for this or just a recommendation to use valign -property?

The code:

```
filterXSS( content,{
  whiteList: filterList,
  stripIgnoreTag: true,
  stripIgnoreTagBody: ['script']
});

var filterList: {
          ...
          table:  ['width', 'border', 'align', 'valign','style','class'],
          tbody:  ['align', 'valign','style','class'],
          td:     ['width', 'rowspan', 'colspan', 'align', 'valign','style','class'],
          tfoot:  ['align', 'valign','style','class'],
          th:     ['width', 'rowspan', 'colspan', 'align', 'valign','style','class'],
          thead:  ['align', 'valign','style','class'],
          tr:     ['rowspan', 'align', 'valign','style','class']
}
```

**Comment by leizongmin** [comment]
I am very sorry that the default `whiteList` is incomplete, you can specify a custom `whiteList`. For this example, just add `vertical-align` to the `td` tag:

```javascript
// get a copy default whiteList
var filterList = filterXSS.getDefaultWhiteList();

// add vertical-align to the td tag
filterList.push('vertical-align');

// call filterXSS()
filterXSS( content,{
  whiteList: filterList,
  stripIgnoreTag: true,
  stripIgnoreTagBody: ['script']
});
```

**Comment by ankero** [comment]
Hi,

Thanks for your reply. The problem isn't the whitelist, I assume, since the 'vertical-align' is a style attribute. So here's an example what html I filter:

<table style="width: 100%;">
<tbody>
<tr>
<td style="width: 50%; vertical-align: top;">column 1</td>
<td style="width:50%; vertical-align: top;">column 2</td>
</tr>
</tbody>
</table>

the output I get is:

<table style="width: 100%;">
<tbody>
<tr>
<td style="width: 50%;">column 1</td>
<td style="width:50%;">column 2</td>
</tr>
</tbody>
</table>

So the vertical-align property gets removed for some reason. Although the width attribute is kept.

**Comment by leizongmin** [comment]
The content of `style` attribute is processed by [the `cssfilter` module](https://github.com/leizongmin/js-css-filter), you can specify the custom css `whiteList` like this:

```javascript
myxss = new xss.FilterXSS({
  css: {
    whiteList: {
      position: /^fixed|relative$/,  // use RegExp to test
      top: true,                               // true means allow any value
      left: false,                              // false means don't allow
    }
  }
});
html = myxss.process('<script>alert("xss");</script>');
```

**If you don't want to use a css white list (just allow any content of the style attribute), you can specify `css: false` to disable it:**

```
myxss = new xss.FilterXSS({
  css: false,
});
html = myxss.process('<script>alert("xss");</script>');
```

I have fixed some problems about this issue https://github.com/leizongmin/js-xss/commit/857fa9de67b1fbb04051e88f8a3f16f6162d9a12 

**Please install the new version: `xss@0.2.7`**

**Comment by ankero** [comment]
Thanks for a great response. I'll implement a custom css filter and double check that I have the newest version running.
