### ISSUE TITLE
xss attack through style attribute

### ISSUE THREAD

**Issue by sjoerdvisscher** [leizongmin/js-xss#70]
Hi,

First of all, thank you for this nice library! Your library is the only one I could find that allows filtering on css.

However, I hoped it would filter out xss hacks in css by default, in particular the `background: url(javascript:...)` hack.

I now have added:

    css: {
      onAttr(name, value) {
        if (value.toLowerCase().indexOf('javascript:') != -1) {
          return '';
        }
      },
    },

to the options, which I think takes care of this.

I think you should add this filter by default or at least warn that your library doesn't catch this xss issue. Thank you!

**Comment by leizongmin** [comment]
I just review the test code, the xss module will filter style attribute which cantains `expression:` and `javascript:`, can you tell me which xss module version do you use?

**Comment by sjoerdvisscher** [comment]
Oh, my mistake, I didn't test this properly!
I'm very sorry!
