### ISSUE TITLE
Filter iframe tags based on their src origin

### ISSUE THREAD

**Issue by pgilad** [leizongmin/js-xss#75]
My use case is:
1. Allow iframe tags (and white listed attrs) if src is from youtube
2. Otherwise filter out the tag entirely

I can't find out how to achieve this using current callbacks. Seems you can either accept the tag or not.

**Comment by leizongmin** [comment]
I think you need to set up a custom `safeAttrValue` function, see https://github.com/leizongmin/js-xss/issues/52

**Comment by pgilad** [comment]
Thanks looks like that could solve it
