### ISSUE TITLE
Need support for ftp link

### ISSUE THREAD

**Issue by huhamhire** [leizongmin/js-xss#77]
I need to set ftp link for `a` tag, which is something like:
```html
<a href="ftp://example.com/test.xlsx">test.xlsx</a>
```
And XSS only allows `http`, `https`, `mailto` links to be set for `a` tag. When I tried to set an ftp link, the href value would be dropped.
```javascript
> new XSS.FilterXSS().process('<a href="ftp://example.com/test.xlsx">test.xlsx</a>')
'<a href>test.xlsx</a>'
```
I would like to know why you limit link protocols to `http`, `https`, `mailto`? What if someone wants to use protocol like `steam://`?

**Comment by wujohns** [comment]
I had the same problem rencently. There is a situation I need to set ftp link too.

**Comment by leizongmin** [comment]
You need to set up a custom `safeAttrValue` function, see https://github.com/leizongmin/js-xss/issues/52

**Comment by wujohns** [comment]
@leizongmin 偶遇老雷～

**Comment by huhamhire** [comment]
@leizongmin Thanks, `safeAttrValue` works for me.
