### ISSUE TITLE
Escaping standalone attribute strings

### ISSUE THREAD

**Issue by iFarmGolems** [leizongmin/js-xss#79]
Hey,

Is it possible to escape standalone attribute strings?
What if I programatically assign some strings into my attributes and then render them, like:

```
jQuery('#myDiv').attribute({
  title: response.title
})
```

Is there any way to handle this?

**Comment by leizongmin** [comment]
I am very sorry for my poor English. I don't clear understand what you mean.

**Comment by iFarmGolems** [comment]
Ah, sorry, no problem :)

I will provide an example:

Lets say I have already created HTML element like this:
`<div id='abc'></div>`

Then I want to assign a title to it:
```
jQuery('#abc').attr('title', someStringFromDatabase)
```
But that is dangerous because I did not sanitize `someStringFromUser`

I am asking if it's possible to do something like...
```
jQuery('#abc').attr('title', filterATTR(someStringFromUser))
```
The `filterATTR` function would look at the attribute string and sanitize it if it would be harmful.
