### ISSUE TITLE
能否指定白名单的某个tag允许所有属性？

### ISSUE THREAD

**Issue by lipten** [leizongmin/js-xss#80]
遇到一个需求，在富文本中可以插入视频，但是各大网站的视频插入代码都有各种各样的属性，我不想一个一个的加白名单，希望能允许一个tag的所有属性都白名单，类似下面的写法，或者直接传正则岂不是更好？！
```
var options = {
  whiteList: {
    embed: [‘*’]
  }
};
```

**Comment by leizongmin** [comment]
目前是可以允许某个标签前缀的，允许某个标签的所有属性也可以通过自定义一些处理函数（如`onIgnoreTagAttr`）来实现，具体可以参考文档说明。

目前无计划在白名单语法中定义允许所有属性的方法。
