### ISSUE TITLE
使用默认配置时markdown的引用语法>被转义了

### ISSUE THREAD

**Issue by xiaoshan5733** [leizongmin/js-xss#82]
请问如何配置才能既不影响正常过滤还能兼顾markdown语法不受影响呢

**Comment by leizongmin** [comment]
你的意思是Markdown生成的HTML有些标签被转义了吧？如果是这种情况，你配置自己的白名单规则，将这些被转义的标签设置到白名单里就可以了。比如：

```javascript
// 获得一份默认的白名单
var whiteList = xss.getDefaultWhiteList();
// 修改自己的白名单规则
whiteList.tag = ['attribute1', 'attribute2'];
// 执行XSS过滤
var source = '<p>Hotel Kadi Palace is located in the <strong>heart </strong>of the <strong>historic center of Florence </strong>'; 
var html = xss(source, {whiteList: whiteList});
console.log(html);
```

**Comment by xiaoshan5733** [comment]
不是标签被转义，是符号“>”被转义了比如我的markdown内容如下：

    
<u>粗体</u>

> 引用
    

经过jsxss后会变成
    
<u>粗体</u>

&amp; 引用

**Comment by xiaoshan5733** [comment]
手机码字不好打代码，稍等我电脑修改下

**Comment by xiaoshan5733** [comment]
@leizongmin

**Comment by leizongmin** [comment]
如果是HTML的话，`>`被转义成了`&amp;`会影响显示效果吗？

**Comment by xiaoshan5733** [comment]
不是html啊  是转html之前就被转义了导致无法正常转成html

**Comment by xiaoshan5733** [comment]
我上面贴的代码属于xss的正常处理吗

**Comment by leizongmin** [comment]
`>`被转成`&amp;`是`xss`模块的正常处理。但是我看你的描述不能保证你的情况是在`xss`中处理的。
正常顺序应该是`xss(markdown(input))`。
